# Generated by Django 4.2.7 on 2023-11-13 17:47

import keyring.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', keyring.fields.KeyringField()),
                ('text', keyring.fields.KeyringField()),
                ('room', keyring.fields.KeyringField()),
                ('user_encrypted_with_key', models.IntegerField(editable=False, null=True)),
                ('user_digest', models.TextField(editable=False, null=True)),
                ('text_encrypted_with_key', models.IntegerField(editable=False, null=True)),
                ('room_encrypted_with_key', models.IntegerField(editable=False, null=True)),
                ('room_sha_digest', models.TextField(editable=False, null=True)),
            ],
        ),
    ]
